name: Pull Request Check

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: echo "✅ Running tests on pull request..."